# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_centrality_vertex - parallel function
#'
#' sample is used to estimate timing, by calculating centrality from just a few
#' vertices.
#' @noRd
rcpp_centrality <- function(graph, vert_map_in, dist_threshold, edge_centrality, sample) {
    .Call(`_exposure_rcpp_centrality`, graph, vert_map_in, dist_threshold, edge_centrality, sample)
}

#' rcpp_flows_exposure
#'
#' @param graph The data.frame holding the graph edges
#' @param vert_map_in map from <std::string> vertex ID to (0-indexed) integer
#' index of vertices
#' @param fromi Index into vert_map_in of vertex numbers
#' @param k Coefficient of (current proof-of-principle-only) exponential
#' distance decay function.
#'
#' @noRd
rcpp_flows_exposure <- function(graph, vert_map_in, fromi, k, dens, tol) {
    .Call(`_exposure_rcpp_flows_exposure`, graph, vert_map_in, fromi, k, dens, tol)
}

#' rcpp_points_index_par
#'
#' Get index of nearest vertices to list of points
#'
#' @param graph Rcpp::DataFrame containing the graph
#' @param pts Rcpp::DataFrame containing the routing points
#'
#' @return 0-indexed Rcpp::NumericVector index into graph of nearest points
#'
#' @noRd
rcpp_points_index_par <- function(xy, pts) {
    .Call(`_exposure_rcpp_points_index_par`, xy, pts)
}

